pipelines:
  test-pipeline:
    group: test-group
    locking: on
    materials:
      system_git:  # this is the name of material
        git: git@github.com:nixxxon/test.git
        shallow_clone: true
    stages:
      - test-stage:
          clean_workspace: true
          elastic_profile_id: "test"
          jobs:
            test-job:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "HELLO TEST"

environments:
  test-environment:
    pipelines:
      - test-pipeline
